### ISSUE TITLE
IE 11 - syntax error at colorPick.js (132,51)

### ISSUE THREAD

**Issue by syserg** [philzet/ColorPick.js#10]
I found a problem in IE11 with JQuery.each code block. IE write "syntax error"
`jQuery.each(this.palette, (index, item) => {
		        $("#colorPick").append('<div class="colorPickButton" hexValue="' + item + '" style="background:' + item + '"></div>');
			});`

solved the problem:
`jQuery.each(this.palette, function (index, item)  {
		        $("#colorPick").append('<div class="colorPickButton" hexValue="' + item + '" style="background:' + item + '"></div>');
			});`

> the issue occurs on line 143

**Comment by tamaskan** [comment]
I can confirm an similar syntax-error in IE and Safari on line 143: "unexptected token >"
