### ISSUE TITLE
Using the plugin twice

### ISSUE THREAD

**Issue by kunalgulati16** [philzet/ColorPick.js#11]
I am trying to use this plugin twice, each time for different event binding. 
`<div class="colorPickSelector" id="color1"></div><h6>Error Bars</h6>`
` <div class="colorPickSelector" id="color2"></div><h6>Data Point</h6><br>`

How to modify the script, by applying the changes for 2 different events??

**Comment by philptr** [comment]
Hi @kunalgulati16! Please take a look at the new demo. I've modified it to support multiple instances on one page.

**Comment by 1HighNoon1** [comment]
Hi, i am using your plugin with Xtemplate. I cant use diffrent ID fot separate color pickers and hidden iniputs. How can I modify script for insert color values through "THIS"?

**Comment by 1HighNoon1** [comment]
Ок, solve this by myone 
add in the hidden input attr <input type="hidden" data_to_bd="" class="ColorSelector_input" >
and modify  $('.colorPickButton').click(function(event) {
by string 
$(this).closest('.colorPickSelector').find('.ColorSelector_input').attr('data_to_bd',$(event.target).attr('hexValue'));
