### ISSUE TITLE
Mixed Content loading Blocked While Site Run in HTTPS.

### ISSUE THREAD

**Issue by hemendra12111** [philzet/ColorPick.js#13]
I have used following css in cdn (https://www.jqueryscript.net/demo/Flat-HTML5-Palette-Color-Picker-For-jQuery-colorPick-js/colorPick.css). it's show mixed content issue when I load in HTTPS.
Because fonts are loading in http: mode not the https:

http://fonts.gstatic.com/s/opensans/v13/cJZKeOuBrn4kERxqtaUH3bO3LdcAZYWl9Si6vvxL-qU.woff

**Comment by tersoo-atsen** [comment]
I have just run into this myself. The problem is the line importing external font from google.
Looks like editing the using HTTPS instead of HTTP in URL resolved this issue.

**I am not using the CDN!**
